# Generated by Django 6.1.1 on 2026-09-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Commentary",
        ),
    ]
